cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "git"
brew "jq"
brew "yarn"
brew "zsh-completions"
brew "mysql"

cask "ngrok"
cask "google-chrome"
cask "slack"
cask "iterm2"
cask "docker"
cask "google-japanese-ime"
cask "figma"
cask "1password"